#!/bin/sh
has() {
  case "$(command -v $1 2>/dev/null)" in
    alias*|"") return 1
  esac
}
shcat(){
  out="$(while read -r p || [ -n "$p" ]; do 
    IFS=""; echo "$p"
  done <&0)"; IFS=""; echo "$out"
} # puresh cat replacement
# input handling is done a on per call basis

deps() {
  missing=0
  for i in jq curl pup; do
    has $i || { echo "$i is missing"; missing=$((missing + 1)); }
    [ $missing -gt 0 ] && exit 1
  done
}
auth() {
  [ -f ./authkeys ] && { . ./authkeys; }
  [ "$URL" ] || { # checks if ./authkeys was sourced, ignoring ~/.cache/fedish/authkeys if it was
    [ -f "${XDG_CACHE_HOME:-$HOME/.cache/}/fedish/authkeys" ] && {
      . "${XDG_CACHE_HOME:-$HOME/.cache/}/fedish/authkeys"
    }
  }
  [ ! $AUTHKEY ] && { 
    export USERKEY=$(curl -sX "POST" -d client_id=$CLID -d client_secret=$CLSEC -d grant_type="refresh_token" -d refresh_token=$REKEY -L "${URL}/oauth/token" | jq .access_token -r)
  } || {
    export USERKEY=$AUTHKEY
  }
  CHURL=$(curl -sH "Authorization: Bearer $USERKEY" -L "${URL}/api/v1/accounts/verify_credentials" | jq .url -r | sed -E -e 's/users.*//' -e 's/@.*//')
  ## handle trailing slash
    while [ "${URL%/}" != "$URL" ]; do URL="${URL%/}"; done
    while [ "${CHURL%/}" != "$CHURL" ]; do CHURL="${CHURL%/}"; done
  ##
  [ "$CHURL" != "$URL" ] && {
    echo "ERROR: CHURL AND URL DO NOT MATCH... POSSIBLE VERIFICATION ISSUE"
    IFS=""; printf "'%s' != '%s'" "$CHURL" "$URL"
    echo "CANNOT PROCEED..."
    exit 1
  }
  [ $USERKEY ] || { echo '$USERKEY IS EMPTY?? AUTH ERROR... FAILING...'; exit 1; }
  [ "$1" ] && { echo "$USERKEY"; exit 0; } 
}
usage() {
  shcat << 'EOF'
Fedish: 
  ~ POSIX sh fediverse client
Usage:
  echo "THIS IS A POST" | ./post [MEDIA] <LOCATION OF MEDIA>
    - Makes a post with the contents of the pipe
    - [MEDIA]: Can be set to enable posting of media, location of said media is required...
    - <LOCATION OF MEDIA>: Local location of media
      - IE: ./blank.png
  ./timelines/[home|local|public]
    - Prints the contents of <> timeline to stdout
      - IE: ./timelines/home
  ./interact <ID> [ACTION]
    - Interacts with a post!
    - <ID>: Interacts with this post
    - [ACTION]: Type of interaction:
      - [star|fav] & [boost|reblog]
  ./fedish gen <URL>
    - Outputs gen info used by "https://www.thatgeekyweeb.github.io/fedish/" for setup
    - <URL>: Must be set, is the base domain of your instance, prefixed with `http(s)://`
      - IE: ./fedish gen "https://disqordia.space/"
  ./fedish help
    - Prints this silly uwu
---
EOF
}
runpost() {
  postemp=$(mktemp); shcat > $postemp
  IFS=""; printf 'POST IS:\n%s' "$(shcat < $postemp)"; echo
  ## Media handling
  [ "$1" = "media" -a "$2" ] 2>/dev/null && {
    unset IFS
    ls $2 >/dev/null && {
      echo "Adding $2 as post media"
      MID="=$(curl -sX "POST" -L -H "Authorization: Bearer $USERKEY" -F file=@${2} "${URL}/api/v1/media" | jq .id -r)"
      echo "$MID"
    } || { echo "$2 DOES NOT EXIST!?... FAILING"; exit 1; } 
  }
  ##
  curl -sX "POST" -H "Authorization: Bearer $USERKEY" -d status="$(shcat < $postemp)" -L "${URL}/api/v1/statuses" -d media_ids[]${MID} >/dev/null
  # $MID is empty when $1 != media, but is equal to `=ID` when media is enabled
  # -d media_ids[] # Has no effect, but `=null` or `=` causes a server error 
  rm $postemp
}
tm() {
  curl -H "Authorization: Bearer $USERKEY" -Ls "$URL//api/v1/timelines/${1:-home}?local=${2:-false}" | { 
    jq '.[] | [.account["username"],.content,.media_attachments[].url,.id]' -r | { 
       sed -E 's/~/FEDISHMARK/g' | tr '\n' '~' | sed -E -e 's/"//g' -e '/\[/{s//######/;:a' -e '$!N;$!ba' -e '}' -e 's/~\[/~######/g' -e 's/\]~/######~/g' -e 's/\,~/:~/g' | tr '~' '\n' | sed -E -e '/^$/d' -e 's/^[[:blank:]]*//g' -e '/null/d' -e 's/:[[:blank:]][[:blank:]]/: /' -e 's/<span>//g' -e 's/<\/span>//g' | pup 'text{}' -p | tr '\n' '~' | sed -E -e 's/~:~/~/g' -e 's/~ //g' -e 's/:~~/:~/g' -e 's/~~######/~######/g' -e 's/######~~/######~/g' | tr '~' '\n' | sed -E 's/FEDISHMARK/~/g'
    }
  } 
}
act() {
  case $2 in
    star|fav|favourite)
      curl -sX "POST" -H "Authorization: Bearer $USERKEY" -L "$URL/api/v1/statuses/${1}/favourite" >/dev/null
    ;;
    boost|reblog)
      curl -sX "POST" -H "Authorization: Bearer $USERKEY" -L "$URL/api/v1/statuses/${1}/reblog" >/dev/null
    ;;
  esac
}
####
# Begin
[ "$2" = "help" -o "$1" = "help" ] 2>/dev/null && { usage; exit 0; } 
[ "$(basename $0)" = "fedish" -a "$1" != "gen" -a "$1" != "userkey" ] && { usage; exit 1; }
deps
case "$1" in
  'gen')
    curl -X POST -d client_name=fedish -d redirect_uris="${3:-https://thatgeekyweeb.github.io/fedish/callback}" -d scopes='read write follow push' -Ls "$2/api/v1/apps" | jq 
    exit 0
    ;;
  'userkey')
    auth _ # _ is Placeholder
    ;;
  '?'|'h'|'-h'|'--help')
    usage; exit 0
    ;;
  *)
    auth
    case "$(basename $0)" in
      post)
        case "$1" in
          'help')
            usage; exit 0
            ;;
          'media')
            runpost "media" $2
            ;;
          *)
            runpost
            ;;
        esac
        ;;
      home)
        tm "home"
        ;;
      public)
        tm "public"
        ;;
      local)
        tm "public" "true"
        ;;
      interact)
        [ ! "$1" ] && { echo "POST ID MISSING?!... FAILING BEFORE I KILL FEDI"; exit 1; }
        act "$1" "${2:-star}"
        ;;
    esac
    ;;
esac
####
